"""
Database Access Facade for Equity Research App.

This module provides a backward-compatible facade for the modularized database
architecture in `core.db`. All symbols, connections, migrations, compliance logs,
and queries are implemented in `core.db.*` and re-exported here to ensure 100%
compatibility across all existing imports throughout the codebase.
"""

from normalizer import clean_ticker, extract_citations_from_report
from core.db import (
    IST,
    _CACHED_SUPABASE_URL,
    _DB_INITIALIZED,
    _DB_INIT_LOCK,
    _PooledConnectionProxy,
    _acquire_connection_from_pool,
    _get_pg_pool,
    get_supabase_url,
    get_placeholder,
    get_db_connection,
    get_db_path,
    init_db,
    MANDATORY_SEBI_DISCLAIMER,
    log_compliance_event,
    get_compliance_audit_logs,
    _format_timestamp,
    save_report_to_archive,
    get_archived_reports,
    get_report_by_ticker,
    get_archived_reports_sync,
    get_report_by_ticker_sync,
    get_report_revisions,
    get_revision_by_id,
    get_watchlist,
    add_to_watchlist,
    remove_from_watchlist,
    is_ticker_in_watchlist,
    update_watchlist_scan_state,
    record_alert_event,
    get_alert_events,
    mark_alert_as_read,
    mark_all_alerts_as_read,
    dismiss_alert,
    dismiss_all_alerts,
    get_unread_alert_count,
    record_usage_event,
    _build_telemetry_time_filter,
    get_site_usage_summary,
    get_session_journeys,
    get_user_usage_analytics,
    get_system_setting,
    set_system_setting,
    get_or_create_user,
    get_user_by_id,
    get_user_by_email,
    get_user_credits_balance,
    deduct_user_credits,
    add_user_credits,
    get_user_transactions,
    get_user_usage_history,
    get_all_billables,
    get_revenue_analytics_summary,
    process_refund,
    create_support_ticket,
    get_support_tickets,
    update_ticket_status,
    get_open_tickets_count,
    __all__ as _core_db_all,
)

__all__ = list(_core_db_all) + [
    "clean_ticker",
    "extract_citations_from_report",
]
